[package]
name = "rust-rpi-playground"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "hello_uart"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
postcard = "1.0.0"
rppal = "0.14.1"
serde = "1.0.160"
